spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username: root
    password: 0174014XZP
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.peng.blog: info
  file: log/blog-pro.log

server:
  port: 80
